baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

title = "Esprim's website ₿"

canonifyURLs = true
enableEmoji = true
#googleAnalytics = "UA-XXXXXX-1"



[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Esprim LTD"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Esprim's website"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Coming soon..."
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "nostr"
    name       = "Nostr"
    url        = "/.well-known"





[[params.social]]
    title = "Email"
    url = "mailto:j@esprim.io"
[[params.social]]
    title = "Follow @esprimio"
    url = "https://twitter.com/esprimio"
[[params.social]]
    title = "Github"
    url = "https://github.com/esprimio"
#[[params.social]]
#    title = "Facebook"
#    url = "https://facebook.com/johndoe"
